name: 'Flyte Run Action'
description: 'Greet someone'
inputs:
  version:  # id of input
    description: 'Who to greet'
    required: true
runs:
  using: "composite"
  steps:
    - name: Setup docker tag.
      run: |
        echo "IMAGE_TAG=ghcr.io/kimjunil/action-test:${{ inputs.version }}" >> $GITHUB_ENV
      shell: bash
    - name: Docker Setup docker/setup-buildx-action
      uses: docker/setup-buildx-action@v2.1.0
    - name: Docker Login
      uses: docker/login-action@v2.1.0
      with:
        registry: ghcr.io
        username: ${{ secrets.GH_USER }}
        password: ${{ secrets.GH_TOKEN }}
    - name: Docker build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: ${{ env.IMAGE_TAG }}
