name: 'Flyte Run Action'
description: 'Greet someone'
inputs:
  version:  # id of input
    description: 'Who to greet'
    required: true
runs:
  using: "composite"
  steps:
    - name: Setup docker tag.
      run: |
        echo "IMAGE_TAG=ghcr.io/kimjunil/action-test:${{ inputs.version }}" >> $GITHUB_ENV
        echo "GH_USER=$GH_USER" >> $GITHUB_ENV
        echo "GH_TOKEN=$GH_TOKEN" >> $GITHUB_ENV
        echo "IMAGE_TAG=ghcr.io/kimjunil/action-test:${{ inputs.version }}" >> $GITHUB_ENV
      shell: bash
    - name: Docker Build & Push
      run: |
        docker login ghcr.io -u ${{ env.GH_USER }} -p ${{ env.GH_TOKEN }}
        docker build -t ${{ env.IMAGE_TAG }} .
        docker push  ${{ env.IMAGE_TAG }}
      shell: bash
