name: 'Hello World'
description: 'Greet someone'
inputs:
  gh-token:  # id of input
    description: 'Who to greet'
    required: true
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: "composite"
  steps:
    - name: Setup docker tag.
      run: |
        echo "VERSION=`git rev-parse HEAD`" >> $GITHUB_ENV
        echo "IMAGE_TAG=ghcr.io/kimjunil/action-test:${{ env.VERSION }}" >> $GITHUB_ENV
      shell: bash
    - name: Docker Setup docker/setup-buildx-action
      uses: docker/setup-buildx-action@v2.1.0
    - name: Docker Login
      uses: docker/login-action@v2.1.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.gh-token }}
    - name: Docker build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: ${{ env.IMAGE_TAG }}

    - run: echo Hello .
      shell: bash
    - id: random-number-generator
      run: echo "::set-output name=random-number::$(echo $RANDOM)"
      shell: bash
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash          
    - run: goodbye.sh
      shell: bash